variable = 'yield' ;
f1 = sprintf('/Volumes/Reacher/GGCMI/AgMIP.output/CMIP_emulated_work/A1_v2.5_UKESM1-0-LL_ssp126_20210531_ph2bl_intpinfs_rmolend_fake1k/emu_EPIC-TAMU/2015-2024/%s.out.gz', ...
    variable) ;
f1 = sprintf('/Volumes/Reacher/GGCMI/AgMIP.output/CMIP_emulated_work/A1_v2.5_UKESM1-0-LL_ssp126_20210531_ph2bl_intpinfs_rmolend_fake1k.real/emu_EPIC-TAMU/2015-2024/%s.out.gz', ...
    variable) ;
% f2 = sprintf('/Volumes/Reacher/GGCMI/AgMIP.output/CMIP_emulated_work/A1_v2.5_UKESM1-0-LL_ssp126_20210616_ph2bl_intpinfs_rmolend_fake1k/emu_EPIC-TAMU/2015-2024/%s.out.gz', ...
%     variable) ;
v1 = lpjgu_matlab_read2geoArray(f1, ...
    'force_mat_save', false, 'force_mat_nosave', true, ...
    'verboseIfNoMat', false) ;
v2 = lpjgu_matlab_read2geoArray(f2, ...
    'force_mat_save', false, 'force_mat_nosave', true, ...
    'verboseIfNoMat', false) ;

max(abs(v1.garr_xv-v2.garr_xv),[],1)